version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: website_postgres
    environment:
      POSTGRES_DB: website_db
      POSTGRES_USER: website_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - website_network

  redis:
    image: redis:7-alpine
    container_name: website_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - website_network

volumes:
  postgres_data:
  redis_data:

networks:
  website_network:
    driver: bridge