// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dembuvipwnfolksvqygl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWJ1dmlwd25mb2xrc3ZxeWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjE4ODAsImV4cCI6MjA2ODMzNzg4MH0.ZjXV_HFJ4vp98ZxFBpQbtH7VUO4R3lzi_QzpgYGmsMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});